### ISSUE TITLE
Collection row editing has no implicit hold or hold-placeholder rendering

### ISSUE THREAD

**Issue by brylie** [brylie/compendium#247]
## Problem

`docs/prd.md` line 155's own acceptance criterion says: "Given an agent holds a set of records spanning a Document block and a Collection row in the same call, then both are held, written, and released through the identical API pattern — the agent does not need modality-specific logic to coordinate a mixed-type batch."

The server-side half of this already holds: `src/lib/server/holds.ts` and the `hold_records` MCP tool are fully generic over record IDs, with no `parentId`/`isCollectionRow` special-casing — an agent can already hold and write a Collection row exactly like a Document block.

The **UI** half is Document-only. `claimBlockPresence`/`releaseBlockPresence`/`subscribeHeldByOthers` (`src/lib/client/presence.ts`) and the hold-shimmer/avatar placeholder are wired up only in `src/routes/space/[spaceId]/doc/[id]/+page.svelte`. No Collection-row editing surface — `PropertyValueCell`, Table/Board/Calendar's own cells, or the record detail pane (#154) — claims an implicit hold on focus, or renders any indication that another actor (human or agent) currently holds the row.

## Impact

If an MCP agent holds and is mid-write on a Collection row's property (via `hold_records` + `write_record`), a human editing that same row concurrently through Table, Board, Calendar, or the record detail pane gets zero visual warning — no shimmer, no avatar — unlike the Document editor, where this exact scenario is the collaboration UX the PRD calls out as a core acceptance bet. This is not a data-loss bug (each property is its own `Y.Map` entry per `data-model.md` §4, so the CRDT still merges correctly at the field level) — it's a silent-conflict-visibility gap: a human has no way to know they're editing over an agent's in-flight write, or vice versa.

## Proposed outcome

Collection row editing surfaces claim/release an implicit hold via cursor/focus presence the same way `BlockEditor`/the Document page do, and render the same shimmer/avatar placeholder when a row (or a specific property cell, if finer granularity turns out to matter) is held by another actor.

- [ ] `PropertyValueCell`/its callers (Table, Board, Calendar, and the record detail pane) claim an implicit hold on the record when a cell gains focus, and release it on blur — mirroring `claimBlockPresence`/`releaseBlockPresence`'s existing Document-editor usage.
- [ ] The same surfaces subscribe to `subscribeHeldByOthers` and render the existing shimmer/avatar placeholder treatment when the focused/displayed row is held by another actor.
- [ ] Decide and document the hold granularity for a Collection row (whole-record vs. per-property-cell) in `docs/specifications/collaboration.md`, consistent with how a Document block's hold already scopes to one block's content.

Not in scope: any change to the server-side `hold_records`/Awareness mechanism itself, which is already generic — this is a UI wiring gap only.

## Context

- `docs/prd.md` line 155 (acceptance criterion)
- `docs/specifications/collaboration.md` (existing hold/presence contract)
- `docs/specifications/collection-views.md` §8 (documents this as a deliberate scope boundary of #154, since #154's own record detail pane has nothing to match against — no rich-text Collection property type exists yet either, tracked separately)
- Related: #154 (Collection record detail pane), which surfaced this gap while implementing its own attribution section

Done when: a Collection row held by one actor (human cursor/focus or an agent's `hold_records` call) shows the same hold/placeholder treatment to every other viewer of that row — across Table, Board, Calendar, and the record detail pane — that a held Document block already shows today.

**Comment by brylie** [comment]
Set Priority: unset → P1.

This is a collaboration-trust/UX gap, not a data-loss bug — each Collection-row property is its own `Y.Map` entry (`data-model.md` §4), so the CRDT still merges correctly at the field level even without this. That keeps it a notch below P0's data-integrity bar, but it directly closes a gap against `docs/prd.md` line 155's own acceptance criterion (the same class of "PRD says this should already work, UI doesn't" gap #71 and #34 were both P1/P0 for), and the collaboration-awareness UX it's missing (the hold shimmer/avatar) is one of the PRD's own core acceptance bets for Document editing already — this issue is that same bet not yet extended to the Collection surfaces #154 just added a third one of (the record detail pane).

**Comment by brylie** [comment]
Added to 0.5.0 — Stability, Reliability, and QA: the hold/placeholder mechanic is a P0 requirement for Document blocks but was never extended to Collection rows, leaving concurrent row edits with no conflict protection — a correctness gap in the same spirit as #33's agent guardrails.
